version: "3.8"

services:
  fastapi:
    build: .
    container_name: leetcode_execution_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
      - ./kubeconfig-container.yaml:/root/.kube/config
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - KUBECONFIG=/root/.kube/config
      - HTTP_PROXY= ""
      - HTTPS_PROXY= ""
      - http_proxy= ""
      - https_proxy= ""
    networks:
      - app-network
    
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app-network
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

  # pgadmin:
  #   container_name: container-pgadmin
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "127.0.0.1:5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   restart: unless-stopped
