apiVersion: v1
kind: ConfigMap
metadata:
  name: dind-daemon-config
data:
  daemon.json: |-
    {
    "proxies": {
    "http-proxy": "{{ .Values.proxy.http_proxy | quote }}",
    "https-proxy": "{{ .Values.proxy.https_proxy | quote}}"
    },
      "insecure-registries": ["{{ .Values.docker.insecureRegistry }}"]
    }