apiVersion: v1
kind: ConfigMap
metadata:
  name: leetcode-executor-config
data:
  DOCKER_HOST: {{ .Values.docker.host }}
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  http_proxy: ""
  https_proxy: ""
  DATABASE_URL: {{ .Values.database.url }}
  REGISTRY_URL: {{ .Values.registry.url }}
  NAMESPACE: {{ .Values.k8s.namespace }}
