apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-sidecar-config
data:
  DOCKER_HOST: unix:///var/run/docker.sock
  HTTP_PROXY: "http://7.182.101.51:3128"
  HTTPS_PROXY: "http://7.182.101.51:3128"
  http_proxy: "http://7.182.101.51:3128"
  https_proxy: "http://7.182.101.51:3128"
  NO_PROXY: "localhost,127.0.0.1,10.0.0.0/8"
  no_proxy: "localhost,127.0.0.1,10.0.0.0/8"
