apiVersion: v1
kind: ConfigMap
metadata:
  name: leetcode-executor-config
data:
  DOCKER_HOST: unix:///var/run/docker.sock
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  http_proxy: ""
  https_proxy: ""
  DATABASE_URL: postgresql+asyncpg://admin:root@postgres-service:5432/test_db
  REGISTRY_URL: "7.182.100.117:500"
