"""add language to test

Revision ID: 955bf9dc5caf
Revises: b8020033c65c
Create Date: 2025-02-22 22:50:23.227140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955bf9dc5caf'
down_revision: Union[str, None] = 'b8020033c65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_id'), 'language', ['id'], unique=False)
    op.add_column('test', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test', 'language', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_column('test', 'language_id')
    op.drop_index(op.f('ix_language_id'), table_name='language')
    op.drop_table('language')
    # ### end Alembic commands ###
